export const PlayerStats = {
  kills: 'Kills',
  medalXp: 'Medal Xp',
  kdRatio: 'Ratio',
  matchXp: 'Match Xp',
  bonusXp: 'Bonus Xp',
  scoreXp: 'Score Xp',
  wallBangs: 'Wall Bangs',
  score: 'Score',
  totalXp: 'Total Xp',
  timePlayed: 'Time Played',
  headshots: 'Headshots',
  executions: 'Executions',
  assists: 'Assists',
  nearmisses: 'Nearmisses',
  challengeXp: 'Challenge Xp',
  percentTimeMoving: 'Percent Time Moving',
  miscXp: 'Misc Xp',
  rank: 'Rank',
  longestStreak: 'Longest Streak',
  scorePerMinute: 'Score Per Minute',
  damageDone: 'Damage Done',
  distanceTraveled: 'Distance Traveled',
  deaths: 'Deaths',
  damageTaken: 'Damage Taken',
  gulagDeaths: 'Gulag Deaths',
  gulagKills: 'Gulag Kills',
  objectiveBrCacheOpen: 'Objective Br Cache Open',
  objectiveBrDownEnemyCircle1: 'Objective Br Down Enemy Circle 1',
  objectiveBrDownEnemyCircle2: 'Objective Br Down Enemy Circle 2',
  objectiveBrDownEnemyCircle3: 'Objective Br Down Enemy Circle 3',
  objectiveBrDownEnemyCircle4: 'Objective Br Down Enemy Circle 4',
  objectiveBrDownEnemyCircle5: 'Objective Br Down Enemy Circle 5',
  objectiveBrDownEnemyCircle6: 'Objective Br Down Enemy Circle 6',
  objectiveBrDownEnemyCircle7: 'Objective Br Down Enemy Circle 7',
  objectiveBrDownEnemyCircle8: 'Objective Br Down Enemy Circle 8',
  objectiveBrDownEnemyCircle9: 'Objective Br Down Enemy Circle 9',
  objectiveBrDownEnemyCircle10: 'Objective Br Down Enemy Circle 10',
  objectiveBrKioskBuy: 'Objective Br Kiosk Buy',
  objectiveBrMissionPickupTablet: 'Objective Br Mission Pickup Tablet',
  objectiveDestroyedVehicleLight: 'Objective Destroyed Vehicle Light',
  objectiveLastStandKill: 'Objective Last Stand Kill',
  objectiveMunitionsBoxTeammateUsed: 'Objective Munitions Box Teammate Used',
  objectiveReviver: 'Objective Reviver',
  objectiveTeamWiped: 'Objective Team Wiped',
  teamPlacement: 'Team Placement',
  teamSurvivalTime: 'Team Survival Time',
  objectiveDestroyedEquipment: 'Objective Destroyed Equipment',
  objectiveEmpedPlayer: 'Objective Emped Player',
  objectiveEmpedVehicle: 'Objective Emped Vehicle',
  '4objectiveEmpedPlayer': '4 Objective Emped Player',
  objectiveWeaponDropTeammateUsed: 'Objective Weapon Drop Teammate Used',
  objectiveDestroyedVehicleMedium: 'Objective Destroyed Vehicle Medium',
  '2objectiveWeaponDropTeammateUsed': '2 Objective Weapon Drop Teammate Used',
  objectiveTrophyDefense: 'Objective Trophy Defense',
  objectiveAssistDecoy: 'Objective Assist Decoy',
};
